pharmacy/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pharmacyPage.urls')),
]

pharmacyPage/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.conf.urls.static import static

urlpatterns=[
    #Redirigiendo las urls del panel de navegacion nav
    path('administer', views.home, name='home'),
    path('category', views.category, name='category'),
    path('', views.list_products, name='list_products'),
    path('about_us', views.about_us, name='about_us'),

    #Rediriengo las ulrs de la seccion del crud de productos
    path('products', views.products, name='products'),
    path('products/create', views.create, name='create'),
    path('products/edit', views.edit, name='edit'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'),
    path('products/edit/<int:id>', views.edit, name='edit'),

    #Redirigiendo a seccion de loggin y sing up

    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    
    # E-commerce

    path('details_product/<int:pk_test>', views.details_product, name='details_product'),

    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),

    # Categorias
    path('categories', views.categories, name='categories'),
    path('category/<str:cats>/', views.CategoryView, name='category'),

    path('categories/createCategory', views.createCategory, name='createCategory'),
    path('categories/editCategory', views.editCategory, name='editCategory'),
    path('eliminarCategory/<int:id>', views.eliminarCategory, name='eliminarCategory'),
    path('categories/editCategory/<int:id>', views.editCategory, name='editCategory'),

    # Proveedores
    path('suppliers', views.suppliers, name='suppliers'),

    path('suppliers/createSupplier', views.createSupplier, name='createSupplier'),
    path('suppliers/editSupplier', views.editSupplier, name='editSupplier'),
    path('deleteSupplier/<int:id>', views.deleteSupplier, name='deleteSupplier'),
    path('suppliers/editSupplier/<int:id>', views.editSupplier, name='editSupplier'),

    # Factura
    path('invoice', views.invoice, name='invoice'),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pharmacyPage/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total 

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class Supplier(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name="nombre", max_length=50)
    last_name = models.CharField(verbose_name="apellido", max_length=50)
    tel = models.CharField(verbose_name="telefono", max_length=50)
    address = models.CharField(verbose_name="direccion", max_length=100)
    email = models.EmailField(verbose_name="correo", max_length=100)
    documentation = models.CharField(verbose_name="documento", max_length=100)
    description = models.TextField(verbose_name="Descripcion", null=True)

    def __str__(self):
        return self.name 

class CategoryProduct(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, verbose_name="nombre")
    description = models.TextField(
        max_length=200, verbose_name="descripcion", null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, verbose_name="nombre")
    image = models.ImageField(
        upload_to='image/', verbose_name="imagen", null=True)
    description = models.TextField(verbose_name="Descripcion", null=True)
    price = models.FloatField(max_length=100, null=True, verbose_name="precio")
    date_end = models.DateField(null=True, verbose_name="fecha de vencimiento")
    category = models.ForeignKey(CategoryProduct, on_delete=models.CASCADE, default=True, null=False, verbose_name="categoria")
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, default=True, null=False, verbose_name="proveedor")
    amount = models.IntegerField(null=True, verbose_name="cantidad")
    digital = models.BooleanField(default=False,null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    lote = models.IntegerField(null=True, verbose_name="lote")

    def __str__(self):
        return self.name

    def delete(self, using=None, keep_parents=False):
        self.image.storage.delete(self.image.name)
        super().delete()
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    department = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

pharmacyPage/views.py
from importlib.metadata import requires
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django. contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.http import JsonResponse
import json
import datetime

# Create your views here.
from .models import *
from .forms import *
from .decorators import unauthenticated_user, allowed_user, admin_only
from .utils import cookieCart, cartData, guestOrder

""" Mostrando archivo html de la barra de navegacion """

@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
@admin_only
def home(request):
    return render(request, 'pages/home.html')


def category(request):
    return render(request, 'pages/category.html')


def list_products(request):
    showProducts = Product.objects.all()
    categories = CategoryProduct.objects.all()

    data = cartData(request)
    order = data['order']

    context = {'showProducts': showProducts, 'categories': categories, 'order':order}
    return render(request, 'pages/list_products.html', context)


def about_us(request):
    return render(request, 'pages/about_us.html')


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def products(request):
    products = Product.objects.all()
    context = {'products': products, }
    return render(request, 'products/index.html', context)


""" Mostrando CRUD Productos """


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def create(request):
    # request.FILES or None || resepciona archivos o imagenes en el CRUD
    formulario = productForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('products')
    return render(request, 'products/create.html', {'formulario': formulario})


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def edit(request, id):
    product = Product.objects.get(id=id)
    formulario = productForm(request.POST or None, request.FILES or None, instance=product)
    if formulario.is_valid() and request.POST:
        formulario.save()
        return redirect('products')
    return render(request, 'products/edit.html', {'formulario': formulario})


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def eliminar(request, id):
    product = Product.objects.get(id=id)
    product.delete()
    return redirect('products')


""" Mostrando login,register y logout """


@unauthenticated_user
def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('list_products')
        else:
            messages.info(request, 'nombre de usuario o contraseña incorrecto')

    context = {}
    return render(request, 'users/login.html', context)


def logoutPage(request):
    logout(request)
    return redirect('list_products')


@unauthenticated_user
def registerPage(request):
    form = UserRegisterForm()

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data['username']

            group = Group.objects.get(name='customer')
            user.groups.add(group)

            messages.success(request, f'Usuario {username} creado')

            return redirect('login')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)


""" Mostrando E-commerce """


def CategoryView(request, cats):
    category_product = Product.objects.filter(category__name=cats)
    data = cartData(request)
    order = data['order']
    context = {'cats':cats, 'category_product':category_product, 'order':order,}

    return render(request, 'pages/category.html', context)


def details_product(request, pk_test):
    selectProduct = Product.objects.get(id=pk_test)
    showProducts = Product.objects.all()
    showProduct = productDetails(request.POST or None, request.FILES or None, instance=selectProduct)
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    context = {'selectProduct': selectProduct,'items':items, 'order':order, 'cartItems':cartItems, 'showProduct':showProduct, 'showProducts': showProducts}
    return render(request, 'ecommerce/details_product.html', context)


@login_required(login_url='login')
def cart(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    
    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'ecommerce/cart.html', context)


@login_required(login_url='login')
def checkout(request):
    data = cartData(request)
    
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    
    context = {'items':items, 'order':order, 'cartItems':cartItems,}
    return render (request, 'ecommerce/checkout.html', context)


@login_required(login_url='login')
def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']
	print('Action:', action)
	print('Product:', productId)

	customer = request.user.customer
	product = Product.objects.get(id=productId)
	order, created = Order.objects.get_or_create(customer=customer, complete=False)

	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		orderItem.quantity = (orderItem.quantity + 1)
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)

	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)


@login_required(login_url='login')
def processOrder(request):
	transaction_id = datetime.datetime.now().timestamp()
	data = json.loads(request.body)

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
	else:
		customer, order = guestOrder(request, data)

	total = float(data['form']['total'])
	order.transaction_id = transaction_id

	if total == order.get_cart_total:
		order.complete = True
	order.save()

	if order.shipping == True:
		ShippingAddress.objects.create(
		customer=customer,
		order=order,
		address=data['shipping']['address'],
		city=data['shipping']['city'],
		department=data['shipping']['department'],
		zipcode=data['shipping']['zipcode'],
		)

	return JsonResponse('Payment submitted..', safe=False)


@login_required(login_url='login')
def invoice(request):
    data = cartData(request)
    
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']


    context = {'items':items, 'order':order, 'cartItems':cartItems,}
    return render(request, 'ecommerce/invoice.html', context)

""" Mostrando Categorias """


@login_required(login_url='login')
def categories(request):
    categories = CategoryProduct.objects.all()
    context = {'categories': categories, }

    return render(request, 'categories/index.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def createCategory(request):
    categories = CategoryProductFrom(
        request.POST or None, request.FILES or None)
    if categories.is_valid():
        categories.save()
        return redirect('categories')
    context = {'categories': categories}
    return render(request, 'categories/createCategory.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def editCategory(request, id):
    categories = CategoryProduct.objects.get(id=id)
    categories = CategoryProductFrom(
        request.POST or None, request.FILES or None, instance=categories)
    if categories.is_valid() and request.POST:
        categories.save()
        return redirect('categories')
    return render(request, 'categories/editCategory.html', {'categories': categories})


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def eliminarCategory(request, id):
    categories = CategoryProduct.objects.get(id=id)
    categories.delete()
    return redirect('categories')


""" Mostrando Proveedeores """

@login_required(login_url='login')
def suppliers(request):
    suppliers = Supplier.objects.all()
    context = {'suppliers': suppliers, }

    return render (request, 'suppliers/index.html', context)

@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def createSupplier(request):
    suppliers = supplierForm(request.POST or None, request.FILES or None)
    if suppliers.is_valid():
        suppliers.save()
        return redirect('suppliers')
    context = {'suppliers': suppliers}
    return render(request, 'suppliers/createSupplier.html', context)

@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def editSupplier(request, id):
    suppliers = Supplier.objects.get(id=id)
    suppliers = supplierForm(request.POST or None, request.FILES or None, instance=suppliers)
    if suppliers.is_valid() and request.POST:
        suppliers.save()
        return redirect('suppliers')
    return render(request, 'suppliers/editSupplier.html', {'suppliers': suppliers})

@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])

pharmacyPage/templates/products/create.html
{%extends "base.html"%} {% block title %} Añadir Nuevo Producto {% endblock %}
{% block content %}

<div class="card">
  <div class="card-header">
    <strong>Añadir Producto</strong>
  </div>
  <div class="card-body">
    <h4 class="card-title">Informacion del Producto</h4>
    {% include 'products/form.html' %}
  </div>
  <div class="card-footer text-muted"></div>
</div>
{% endblock %}

pharmacyPage/templates/products/edit.html
{%extends "base.html"%} {% block title %} Editar Productos {% endblock %} 
{% block content %}

<div class="card">
  <div class="card-header">
    <strong>Editar Productos</strong>
  </div>
  <div class="card-body">
    <h4 class="card-title">Informacion del Producto</h4>
    {% include 'products/form.html' %}
  </div>
  <div class="card-footer text-muted"></div>
</div>
{% endblock %}

pharmacyPage/templates/products/form.html
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
    <div class="mb-3">

      <label for="" class="form-label">Nombre:</label>
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <input id="" class="form-control" aria-describedby="helpId" placeholder="Nombre" {{ formulario.name | default:'' }}
        </div>
      </div>

      <label for="imageImagen" class="form-label">Imagen:</label>
      {% for campo in formulario  %}
      {% if campo.field.widget.input_type == 'file' and campo.value  %} 
      <br>
      <img src="{{MEDIA_URL}}/imagenes/{{campo.value}}" width="100" alt="" srcset="">
      {% endif %}
      {% endfor %}
      <input type="file" class="form-control" name="image" id="" aria-describedby="helpId" placeholder="Imagen" value="formulario.image">

      <label for="" class="form-label">Descripcion:</label> 
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <textarea id="" class="form-control" aria-describedby="helpId" placeholder="Descripcion" {{ formulario.description | default:'' }}
        </div>
      </div>

      <label for="" class="form-label">Precio:</label> 
      <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input type='float' step='0.00' class="form-control" placeholder="Precio" aria-label="Amount (to the nearest dollar)" {{ formulario.price | default:'' }}
        <span class="input-group-text">.00</span>
      </div>
      
      <label for="" class="form-label">Expiracion:</label>
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <input type="date" dateFormat:'yyyy-MM-dd' id="" class="form-control" aria-describedby="helpId" placeholder="Expiracion" {{ formulario.date_end | default:'' }}
        </div>
      </div>

      <label for="" class="form-label">Categoria:</label>
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <select id="id_category" class="form-control" aria-describedby="helpId" placeholder="Categoria" {{ formulario.category | default:'' }}
        </div>
      </div>

      <label for="" class="form-label">Cantidad:</label>
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <input type="number" id="" class="form-control" aria-describedby="helpId" placeholder="Cantidad" {{ formulario.amount | default:'' }}
        </div>
      </div>

      <label for="" class="form-label">Proveedor:</label>
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <select id="id_supplier" class="form-control" aria-describedby="helpId" placeholder="Proveedor" {{ formulario.supplier | default:'' }}
        </div>
      </div>

      <label for="" class="form-label">Lote:</label>
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <input type="number" id="" class="form-control" aria-describedby="helpId" placeholder="Lote" {{ formulario.lote | default:'' }}
        </div>
      </div>

      {% comment %} <label for="" class="form-label">Fecha de ingreso:</label>
      <div class="d-flex flex-row align-items-center mb-4">
        <div class="form-outline flex-fill mb-0">
          <input type="date" dateFormat:'yyyy-MM-dd' id="" class="form-control" aria-describedby="helpId" placeholder="Fecha de ingreso" {{ formulario.created_at | default:'' }}
        </div>
      </div> {% endcomment %}

    </div>

    <div class="col-12 help-text">{{formulario.errors}}</div>
    
    <input name="" id="" class="btn btn-warning b" type="submit" value="Guardar">
    <a name="" id="" class="btn btn-dark b" href="{% url 'products' %}" role="button">Cancelar</a>
</form>
<style>
  .b{font-weight: bold;}
</style>

pharmacyPage/templates/products/index.html
{%extends "base.html"%}
{% block title %} Lista de Productos {% endblock %}
{% block content %}
<div class="card">
    <div class="card-header">
        <a name="" id="" class="btn btn-dark" href="{%url 'create'%}" role="button"><strong><i class="fa-solid fa-plus"></i> Añadir Producto</strong></a>
    </div>
    <div class="card-body">
        
        <table class="table">

            <thead class="table-white" style="vertical-align: middle;">
                <tr>
                    <th>ID</th>
                    <th>NOMBRE</th>
                    <th>PRECIO</th>
                    <th>IMAGEN</th>
                    <th>EXPIRACION</th>
                    <th>CATEGORIA</th>
                    <th>CANTIDAD</th>
                    <th>PROVEEDOR</th>
                    <th>LOTE</th>
                    <th>FECHA AGREGADO</th>
                    <th>DESCRIPCION</th>
                    <th>ACCIONES</th>
                </tr>
            </thead>

            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{product.id}}</td>
                    <td>{{product.name}}</td>
                    <td>${{product.price|floatformat:2}}</td>
                    <td>
                        <img id="img-product" src="{{product.image.url}}" alt="" srcset="" height="100">
                    </td>
                    <td>{{product.date_end}}</td>
                    <td>{{product.category}}</td>
                    <td>{{product.amount}}</td>
                    <td>{{product.supplier}}</td>
                    <td>{{product.lote}}</td>
                    <td>{{product.date_ordered}}</td>
                    <td>{{product.description|linebreaks|truncatewords:10}}</td>
                    <td id="action"><a name="" id="" class="btn btn-warning" href="{% url 'edit' product.id %}" role="button"><i class="fa-solid fa-pen-to-square"></i></a>
                    &nbsp;
                    <a name="" id="" class="btn btn-dark" href="{% url 'eliminar' product.id %}" role="button"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="card-footer text-muted">
        
    </div>
</div>
<a href="{% url 'home' %}" type="button" 
class="btn btn-dark btn-lg main-btn primary-btn" style="width: auto;margin: 1.5rem 0;">
Regresar</a>
{% endblock %}